### ISSUE TITLE
Example Pong AI toggle confusion

### ISSUE THREAD

**Issue by bluelhf** [sam-astro/Z-Sharp#14]
See this block of code:
https://github.com/sam-astro/Z-Sharp/blob/bbc1e1f16b9f1e59cc533db50b765ca1d0f578b8/examples/Pong-Example-Project/script.zs#L144-L151

Assume `aiOn == true` at the start of the block — would it not be set to false only to immediately be set to true again?

**Comment by sam-astro** [comment]
Thank you! You are totally right, this makes the AI permanently on! I'll be sure to fix this.

**Comment by sam-astro** [comment]
Fixed!
