### ISSUE TITLE
Change Install Check

### ISSUE THREAD

**Issue by ImThereum** [sam-astro/Z-Sharp#16]
Adding checks too the Installer is better since it will detect what MS Visual Runtime and MSVC C++ Redistribute dll's you need and then send out a text box with the text "You need these DLL's: VCRUNTIME140_1.dll".

I'm not totally sure if this should be possible but yeah I think its a "good" idea

If anyone wants too know what im talking about is these MSVC Files:
[https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

This isnt a direct issue but just a recommendation so people don't need to figure out what they need and all of this is pushed onto the Windows side of things.

**Comment by sam-astro** [comment]
I added it to the installation instructions for windows, because actually checking for an installed version and downloading/showing a link seems like a lot of work for something a lot of people won't need.
