### ISSUE TITLE
ZS Syntax on VSC?

### ISSUE THREAD

**Issue by ImThereum** [sam-astro/Z-Sharp#17]
It's probably a good idea making a Syntax on Visual Studio Code since I do program on VSC instead of any other Editior / IDE

**Comment by sam-astro** [comment]
You can do this if you want, but I am not going to since it is not required to use the language.

**Comment by StevenRafft** [comment]
I made an extension really quickly for syntax highlighting only tho, here it is [ZSharp](https://marketplace.visualstudio.com/items?itemName=StevenRafft.zsharp)

**Comment by ImThereum** [comment]
> I made an extension really quickly for syntax highlighting only tho, here it is [ZSharp](https://marketplace.visualstudio.com/items?itemName=StevenRafft.zsharp)

Tysm, I was looking for something like this!
