### ISSUE TITLE
./ZSharp: command not found when trying to run it

### ISSUE THREAD

**Issue by pi141** [sam-astro/Z-Sharp#19]
title

typed in ./ZSharp and the directory like in the readme and it says "./ZSharp: command not found"

**Comment by sam-astro** [comment]
`./ZSharp` is an example location. If you are using a command line or terminal, then you must provide the full path to the executable.

For example:
* If you used the windows installer, in the command line you would type:
     `> "C:\Program Files (x86)\ZSharp\ZSharp.exe" <path to your script>`
* Or if you are using linux you would type:
     `$ <path to zsharp> <path to your script>`
