### ISSUE TITLE
Mac bianaries?

### ISSUE THREAD

**Issue by yescyyt** [sam-astro/Z-Sharp#21]
Will there ever be macOS binaries? Or maybe an installation tutorial for macOS would be another easier option.

**Comment by sam-astro** [comment]
Feel free to port the code and build your own mac binaries, but since I have no access to macOS I can't make my own and test it.

**Comment by dinhndrwmacbook** [comment]
I have the build here:
[ZSharp-Mac-Binaries.zip](https://github.com/sam-astro/Z-Sharp/files/9487090/ZSharp-Mac-Binaries.zip)
