### ISSUE TITLE
Arrays and dictionaries

### ISSUE THREAD

**Issue by SpazElectro** [sam-astro/Z-Sharp#23]
**Is your feature request related to a problem? Please describe.**
I am trying to make a 3D game using Z#, I want to create an array for the enemies, and a dictionary that stores the enemy's data

**Describe the solution you'd like**
I want to be able to make arrays and dictionaries.

**Describe alternatives you've considered**
Having a variable for everything, which was really just spaghetti code
(my code looked sort of like this)
```cs
global int enemies_1_health = 100;
global Sprite enemies_1_sprite = ZS.Graphics.Sprite("./enemy.png", NVec2(250, 250), NVec2(20, 20), 0);
global int enemies_1_movespeed = 1;

global int enemies_2_health = 100;
global Sprite enemies_2_sprite = ZS.Graphics.Sprite("./enemy.png", NVec2(250, 250), NVec2(20, 20), 0);
global int enemies_2_movespeed = 3;
```

and so on...

**Comment by sam-astro** [comment]
Hi, thank you for the suggestion. This is already a planned feature for a future release, but it may be a while.
