### ISSUE TITLE
ImGui in Z# (Intergrated)

### ISSUE THREAD

**Issue by ImThereum** [sam-astro/Z-Sharp#39]
I've been kind of wondering if this is possible but something like a toggle for ImGui would be nice, I kind of want it integrated instead of something like Importing it constantly!

Could there be an Internal ImGui function which could be used for game development?
I'm not sure if it is implanted but would like too see it, I haven't used this for quite some time so I don't know.

Just a simple line like; enable ImGui;
this is probably never going to be used but I'll probably use it since its quite major for games, ImGui is used in a load of big games in companies like Ubisoft so like would be neat to see!

**Comment by 0ALFARSI0** [comment]
just edit the files of the GUI.
