### ISSUE TITLE
Fix installer (SDL2.dll and etc. missing after using installer)

### ISSUE THREAD

**Issue by OrangeLeafDev** [sam-astro/Z-Sharp#4]
![image](https://user-images.githubusercontent.com/70693681/169198475-9abe0081-c396-4142-a33b-05359ef5fed2.png)
![image](https://user-images.githubusercontent.com/70693681/169198483-d5354607-ef18-478c-b15d-95c120bfc38a.png)
![image](https://user-images.githubusercontent.com/70693681/169198505-74df4226-fc25-4969-a165-941640153e81.png)
I have already tried reinstalling, should i just use the regular version?

**Comment by sam-astro** [comment]
I'll work on fixing this issue, it seems the installer forgets to include the required .DLLs. I recommend just using the normal version for now.

**Comment by sam-astro** [comment]
Fixed in the newest version:
[https://github.com/sam-astro/Z-Sharp/releases](https://github.com/sam-astro/Z-Sharp/releases)
