### ISSUE TITLE
macOS Not Supported

### ISSUE THREAD

**Issue by dinhndrwmacbook** [sam-astro/Z-Sharp#46]
**Describe your issue**
So I built this program on macOS but it is not functional, I drag and drop the .zs file, which is Pong-Example-ZSharp And nothing happened

**To Reproduce**
You need to the brew package manager, copy this command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

If you already have the brew package manager

Copy this command:

brew install sdl2_image sdl2_ttf sdl2 git CMake ninja

After you did, clone this project:

git clone https://github.com/sam-astro/Z-Sharp/ 

Go to the directory:

cd /path/to/Z-Sharp/ZSharp

If you did that, Follow this command:

cmake -B build . -G "Ninja"

And then:

cd build && ninja

Now type ./ZSharp **"executable file"**

**Comment by CleanCode-developer** [comment]
There are very few mac users, less than 10. The last mac binary had almost no downloads. If you wish to use this, you can either run the program in a virtual machine, or use the unofficial online compiler and emulator [here](https://yaballang.github.io/docs)
