### ISSUE TITLE
Precompiled Binaries for macOS

### ISSUE THREAD

**Issue by ltecheroffical** [sam-astro/Z-Sharp#49]
**Feature**
Precompiled Binaries for macOS.

**Reason**
I use macOS and don't have Windows or Linux machines.

**Comment by CleanCode-developer** [comment]
he said the same thing to me,
"There are very few mac users, less than 10. The last mac binary had almost no downloads. If you wish to use this, you can either run the program in a virtual machine, or use the unofficial online compiler and emulator [here](https://yaballang.github.io/docs)"
