### ISSUE TITLE
Allow for less accurate syntax (The Application Was Unable To Start Correctly (0xc0000007b))

### ISSUE THREAD

**Issue by 1Chip1** [sam-astro/Z-Sharp#5]
Tried to start a hello world code got this.

**Comment by sam-astro** [comment]
What does your code look like?

**Comment by 1Chip1** [comment]
PLATFORM: Windows
Code:
func main() {
    print "Hello World!"
}

**Comment by sam-astro** [comment]
Haha so the interpreter is very strict on syntax. That means that your code:
```
func main() {
	print "Hello World!"
}
```

Should actually be:
```
func main()
{
	print "Hello World!"
}
```

That should work! The curly brackets need to start on a new line, which will be changed in the future to also start on the same line.

**Comment by 1Chip1** [comment]
Oh! I'm don't usually using this kind of syntax... Thanks!
