### ISSUE TITLE
Linux requirements missing

### ISSUE THREAD

**Issue by azaelreo-dev** [sam-astro/Z-Sharp#52]
**Describe your issue**
Linux requirements for ZS are missing!

**To Reproduce**
1. Go to 'README.md'
2. Look at requirements and find Linux.
3. Where the requirements at???

**Comment by sam-astro** [comment]
I'm not sure what the problem you are having is. This is the current version of the README.md, and it states all of the requirements here:
![Screenshot 2023-02-27 9 04 29 AM](https://user-images.githubusercontent.com/77079540/221584366-103659d7-1930-43a3-936a-2a5a5ef1878e.png)

**Comment by azaelreo-dev** [comment]
My bad, I noticed the "1." before and thought something was supposed to go there. Basically, I looked at install requirements, and thought something should go there.

**Comment by sam-astro** [comment]
haha, that makes sense. I should actually probably put the full names there anyway, just in case anybody is using a package manager that uses different naming conventions that that for them.
