### ISSUE TITLE
When following docs, window opens then immediately closes.

### ISSUE THREAD

**Issue by phofers** [sam-astro/Z-Sharp#57]
As I'm following the docs, the window immediately opens then closes when I run the basic hello world function. The code in my "hello.zs" file is:
`
func Main() {
`
`
    Printl("Hello World!")
`
`
}
`

I then save the file and open it with ZSharp.exe, then the issue occurs.

**Comment by sam-astro** [comment]
That is because the program exits when complete. If you want to see console output, run it in a terminal, just like any other language outside of its debug compilation.

**Comment by phofers** [comment]
Thanks, that was dumb of me.
