### ISSUE TITLE
Unable to run Main.cpp.

### ISSUE THREAD

**Issue by grendizerh** [sam-astro/Z-Sharp#58]
Can’t run Main.cpp, error. Shown:

![image](https://github.com/sam-astro/Z-Sharp/assets/101386337/7f5ba3ac-5a34-4718-a1f1-814b06e4ae00)

I am running this on an iPad 10, please fix this bug.

**Comment by sam-astro** [comment]
In order to compile Z-Sharp, you need to install the [Boost libraries](https://www.boost.org/)
