### ISSUE TITLE
Simple movement not working?

### ISSUE THREAD

**Issue by StevenRafft** [sam-astro/Z-Sharp#6]
**Describe your issue**
Okay so, I'm just starting out on Z#, so I decided to start making a game using it, but i'm getting an issue where the sprite doesn't move? Also, I can't add any empty new lines onto the update function? I get an error for doing that.

**To Reproduce**
Make a new file, add this onto it

```cs
int squareX = 250
int squareY = 250

func Main()
{
    int screenWidth = 500
    int screenHeight = 500

    ZS.Graphics.Init("Title of window", screenWidth, screenHeight)
}

func Start()
{
    Vec2 position = NVec2(squareX, squareY)
    Vec2 scale = NVec2(20, 20)
    float rotation = 0

    global Sprite exampleSprite = ZS.Graphics.Sprite("./square.jpg", position, scale, rotation)
}

func Update()
{
    ZS.Graphics.Draw(exampleSprite)
    if GetKey("W") == true
    {
        squareY -= 10
    }
    if GetKey("S") == true
    {
        squareY += 10
    }
    if GetKey("D") == true
    {
        squareX -= 10
    }
    if GetKey("A") == true
    {
        squareX += 10
    }
}
```

**Comment by StevenRafft** [comment]
Okay so, I just realized the squareX, squareY do not change the actual position, even with a exampleSprite.Position = NVec2(squareX, squareY) in the update function it still does not change it's position.

**Comment by sam-astro** [comment]
It seems to work if you change 
`func Update()`
to
`func Update(deltaTime)`
and add the line
`exampleSprite.position = NVec2(squareX, squareY)`

Using deltaTime is supposed to be optional, so this is a bug. But when making a game, I recommend using this and multiplying it by movement speeds so they are constant.

**Comment by StevenRafft** [comment]
thank you, it works perfectly!

**Comment by StevenRafft** [comment]
Also, about the new lines question, It seems like I can't create any new empty lines, I also can't do things like
`global Sprite player = ZS.Graphics.Sprite("./square.jpg", **NVec2(250, 250)**, size, 0)`
I have to create a new variable just for the parameters.

**Comment by sam-astro** [comment]
Fixed in the newest release
