### ISSUE TITLE
I cannot execute a Z# file...

### ISSUE THREAD

**Issue by imagment** [sam-astro/Z-Sharp#61]
![image](https://github.com/user-attachments/assets/3097b27a-b032-43ac-87cd-699d7c212cf6)

**Comment by imagment** [comment]
it could not run
func Main()
{
	Printl("this is a test:")
}

either

**Comment by sam-astro** [comment]
It worked for me, perhaps this could be due to the fact you are using `v2.0.2` instead of the most recent version of `v2.1.3`

**Comment by imagment** [comment]
Hmmm.... the folder is saying version 2.1.3... but when I run it it is saying version 2.0.2

**Comment by sam-astro** [comment]
I just checked, the most recent linux version should definitely be saying `v2.1.3`. You should re-download it and try again.

**Comment by imagment** [comment]
![Screenshot 2024-09-08 124750](https://github.com/user-attachments/assets/d3324764-b47e-489b-8901-78b08557826e)
![Screenshot 2024-09-08 124800](https://github.com/user-attachments/assets/117a76ed-f199-477f-901c-1f7f911a226f)
![Screenshot 2024-09-08 124812](https://github.com/user-attachments/assets/8f9ca6ea-084d-49ca-9b74-06f6ee555c2f)
![Screenshot 2024-09-08 124817](https://github.com/user-attachments/assets/72b77710-9c4b-4ee4-9a6c-528a550d21f8)
![Screenshot 2024-09-08 124846](https://github.com/user-attachments/assets/e85adbfb-7d87-48ab-b4b9-55bdfb37bdba)
![Screenshot 2024-09-08 124914](https://github.com/user-attachments/assets/7fa41857-9a33-4ccd-8360-ce3bf421753d)
![Screenshot 2024-09-08 124947](https://github.com/user-attachments/assets/8c1249e8-c142-466c-8214-a1456fffbd28)

**Comment by sam-astro** [comment]
Is there a reason you aren't just downloading from the releases?

**Comment by imagment** [comment]
Umm... yes kind of. I am trying to remix this language. 
( It is hard to start from scratch )

**Comment by sam-astro** [comment]
Although I really wouldn't recommend that, if you really want to use ZSharp as a base and not something else, you can just rebuild the linux source using cmake

**Comment by imagment** [comment]
Thanks, but I am kinda new to Cmake, but which one should I use? there are many file that has "CMake" in their names or files that end with .cmake

**Comment by imagment** [comment]
![Screenshot 2024-09-08 135038](https://github.com/user-attachments/assets/c538422f-1e7b-4877-8e48-d483139b0103)
kinda figured it out by googling. but stuck again

**Comment by sam-astro** [comment]
enter directory `linux-build`, delete everything in that directory with `cmake` in its name. Run `cmake ..` then run `make` . If you get the error stating boost is not installed, run `sudo apt-get install libboost-all-dev -y` , then try again. After this you should have the file titled `ZSharp` which you can now run

**Comment by imagment** [comment]
![Screenshot 2024-09-09 154224](https://github.com/user-attachments/assets/fec6b93b-c772-4fcd-bb58-1091b276e5f2)
version upgraded to 2.1.3, but it cannot execute scripts unfortunatly :(

**Comment by sam-astro** [comment]
Use absolute paths
