### ISSUE TITLE
cannot open source file "boost/any.hpp"

### ISSUE THREAD

**Issue by flexlinux** [sam-astro/Z-Sharp#8]
Hi, i was trying to build the source but i always get this error in vs

![image](https://user-images.githubusercontent.com/72740709/169659824-f09008c6-5597-43dc-b979-952b8afc6185.png)

if someone can help me i would be gratefull!

**Comment by sam-astro** [comment]
In order to build from source, you will need to install the Boost libraries. It can be a bit difficult, so I may make a tutorial sometime in the future. But there are already many tutorials you can use to install boost on windows.
