### ISSUE TITLE
Added form editor

### ISSUE THREAD

**Issue by YT-Advanced** [sam-astro/Z-Sharp#9]
Hello, I hope you Z# have an feature like this:
![image](https://user-images.githubusercontent.com/70064328/169679426-b5b2191b-1151-456a-9990-0281b551503e.png)

**Comment by TheAwesome98-Real** [comment]
yes, but it would need to use gtk because that also works on other platforms not just windows.

**Comment by sam-astro** [comment]
I don't ever plan on adding this functionality
